sudo: required
dist: trusty

addons:
  apt:
    sources:
      - chef-stable-trusty
    packages:
      - chefdk

before_script:
    - eval "$(/opt/chefdk/bin/chef shell-init bash)"
    - /opt/chefdk/embedded/bin/chef --version

script: rspec .    
